### PR TITLE
Python3 port

### PR DESCRIPTION
**Pull request by lCharlie123l**
Ported to work on Python 3.4

Removed dependancy on libthumbor as it does not support Python 3.4

### CODE REVIEW

**Comment by lCharlie123l** [comment]
Im looking in to why the tests are failing for python 3

**Comment by lCharlie123l** [comment]
Now working for both python 2.7 and 3.4 and django version 1.7.4 & 1.8.2

**Comment by lCharlie123l** [comment]
This should be ready for merge now :hamburger:

**Comment by Starou** [comment]
Hi @lCharlie123l ,

Thanks for your contribution. I need to review your code before merging it since there are some non-trivial modifications (StringIO, CryptoURL) and not being a Python 3 guy, it may take a while...

By the way, could you squash your commits to something more logical (1commit == 1 feature/bugfix) ?

**Comment by lCharlie123l** [comment]
Hi @Starou ,

No worries, we use your library quite a lot as it's really useful but really needed it to work in Python 3 hence we decided to contribute. Haha that's fine, we'll be pulling the version from my branch in our build script for the time being anyway.

I may not get a chance to squash the commits today but hopefully do by end of Monday for you. The main things I have done to give you an idea with trawling through the commits are as follows:

* Swapped out StringIO for io.BytesIO as this is compatible with Python 2 & 3
* Removed the dependancy on libthumbor & CryptoURL by implementing the tiny piece that was actually used manaully
* Modified all file read and writes to explicitly be in binary mode 
* Fixed the backwards compatibility to django 1.5 & 1.6 for you by adding a conditional use of "@deconstructable" class decorator
* Added Python3 and removed libthumbor from the travis file
* Added some git ignore for virtual environments
* Updated the Readme
* Incremented the version number
* Changed the base level to be non negative in your imports in runtests.py as this makes it both python 2.7 and 3.4 compatible

Hope that helps if you want to review it in the meantime before i get a chance to squash the commits.

Thanks

**Comment by Starou** [comment]
Hey, good to know that this lib is useful to you guys!

I would split your PR in several ones:

1. explicit binary-mode (for the Windows guys)
2. Django-1.5/6 compat
3. Python 3 compat
4. gitignore (if you can convince me that it is useful to someone else and not specific to you!)

No needs to increment the version-number (if you use pip and this is a problem for you, you can use something like `pip install --upgrade --force-reinstall git+https://your/repos.git@your-branch`)

Cheers,

ps: there is no hurry.

**Comment by lCharlie123l** [comment]
Sorry i closed this accidentally whilst trying to squash the commits

**Pull request closed without merging**
